#!/bin/bash
#
# This is to link vim's syntastic-check to a python2 linter.
# NOTE: This workaound is for python2 only! For python3, you can
#       just uncomment the 'let g:syntastic_python_python_exec'
#       line pointing to your python3 venv with your installed linter.
# - Make sure you setup a venv (and update the path below)
#   with a linter of your choosing (in this case, flake8).
# - This script needs to be executable (chmod +x flake8) and
#   put somewhere on your $PATH

source ~/envs/flake/bin/activate
flake8 "$@"

